accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:icecream_id>/', views.detail, name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('delete/<int:pk>',views.delete,name='delete'),
    path('<menu_filter>/', views.home, name='home'),
    path('<menu_filter>/upvote/<int:icecream_id>/', views.upvote, name='upvote'),
    path('<menu_filter>/downvote/<int:icecream_id>/', views.downvote, name='downvote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('new/', views.CreateView.as_view(), name='create'),
]

accounts/models.py
from django.db import models

# Create your models here.

menu/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.urls import reverse


class IceCream(models.Model):
    flavor = models.CharField(max_length=200)
    featured = models.BooleanField()
    base = models.CharField(max_length=20, choices=[    
      ('vanilla', 'Vanilla'),
      ('chocolate', 'Chocolate'),
      ])
    available = models.CharField(max_length=20, choices=[
      ('daily','Daily'),
      ('weekly','Weekly'),
      ('seasonal','Seasonal'),
      ])
    date_churned = models.DateTimeField('date published',default=timezone.now())
    score = models.IntegerField(default=0)

    def __str__(self):
      return self.flavor
    
    def isFresh(self):
      return self.date_churned >= timezone.now() - datetime.timedelta(days=0)

    def get_absolute_url(self):
      return reverse('menu:home',args=('home',))

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.urls import reverse

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    def __str__(self):
      return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('polls:index')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
      return self.choice_text

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
class SignUpView(generic.CreateView):
  form_class = UserCreationForm
  success_url = reverse_lazy('login')
  template_name = 'signup.html'

menu/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import logout as logout_


from .models import IceCream

def is_superuser_check(user):
  return user.is_superuser

def home(request, menu_filter=''):
  if menu_filter == 'home':
    freshest_list = IceCream.objects.all()
  elif menu_filter == 'featured':
    freshest_list = IceCream.objects.filter(featured=True)
  else:
    freshest_list = IceCream.objects.filter(available=menu_filter)

  freshest_list = freshest_list.order_by('-date_churned')
  template = loader.get_template('menu/home.html')
  context = {
      'freshest_list': freshest_list,
  }
  return HttpResponse(template.render(context, request))

def detail(request, icecream_id):
    ic = get_object_or_404(IceCream, pk=icecream_id)
    return HttpResponse("You're looking at %s." % ic.flavor)

def upvote(request, icecream_id, menu_filter='home'):
    ic = get_object_or_404(IceCream, pk=icecream_id)
    ic.score += 1
    ic.save()
    return HttpResponseRedirect(reverse('menu:home', args=(menu_filter,)))

def downvote(request, icecream_id, menu_filter='home'):
    ic = get_object_or_404(IceCream, pk=icecream_id)
    ic.score -= 1
    ic.save()
    return HttpResponseRedirect(reverse('menu:home', args=(menu_filter,)))

class CreateView(UserPassesTestMixin, generic.CreateView):
    model = IceCream
    fields = 'flavor','featured','base','available',
    template_name = 'menu/create.html'

    def test_func(self):
      return self.request.user.is_superuser

    def handle_no_permission(self):
      return redirect('menu:home')
    
class IndexView(generic.ListView):
    template_name = 'menu/index.html'
    def get_queryset(self):
        return IceCream.objects.all()

@user_passes_test(is_superuser_check)
def delete(request, pk, menu_filter='home'):
  ic = get_object_or_404(IceCream, pk=pk)
  ic.delete()
  return HttpResponseRedirect(reverse_lazy('menu:home',args=('home',)))

# class DeleteView(generic.DeleteView):
#     template_name = 'menu/delete.html'
#     model = IceCream
#     success_url = reverse_lazy('menu:home',args=('home',))

def logout(request):
    logout_(request)
    # return HttpResponseRedirect(reverse_lazy('menu:home',args=('home',)))

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404,HttpResponse
from django.template import loader
from django.views import generic
from django.urls import reverse

from .models import Question

# def index(request):
#     question_list = Question.objects.order_by('-pub_date')
#     context = {'question_list': question_list}
#     return render(request, 'polls/index.html', context)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    # by default the context object is named object_list
    context_object_name = 'question_list'

    def get_queryset(self):
        return Question.objects.all()

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    selected_choice = question.choice_set.get(pk=request.POST['choice'])

    selected_choice.votes+=1
    selected_choice.save()
    
    return HttpResponse(reverse('polls:results', args=(question.id,)))

class CreateView(generic.CreateView):
    model = Question
    fields = 'question_text',
    template_name = 'polls/create.html'
    

accounts/templates/signup.html
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>

menu/templates/menu/create.html
<h1>Add a new flavor below!</h1>
<form method='POST'>{% csrf_token %}
  {{form.as_p}}
  <button>Submit</button>
</form>

menu/templates/menu/delete.html
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>

menu/templates/menu/home.html
{% load static %}

<h1> Welcome to Buster's Ice Cream</h1>
{% if request.user.is_authenticated %}
<h3>Welcome {{user.username}}!</h3>
{% else %}
<div><a href="{% url 'login'%}">Login</a> or <a href="{% url 'accounts:signup' %}">Sign Up</a></div>
{% endif %}
<br>
<nav>
  <a href="/menu/home">ALL</a>
  <a href="/menu/featured/">FEATURED</a>
  <a href="/menu/daily/">DAILY</a>
  <a href="/menu/weekly/">WEEKLY</a>
  <a href="/menu/seasonal/">SEASONAL</a>
</nav>
{% if freshest_list %}
    <ul>
    {% for icecream in freshest_list %}
        <li>
          <a href="{% url 'menu:detail' icecream.id %}">{{ icecream.flavor }}</a> 
          <a href="upvote/{{ icecream.id }}">+</a>{{ icecream.score }}<a href="downvote/{{ icecream.id }}">-</a>
          {% if request.user.is_superuser %}
          (<a href="{% url 'menu:delete' icecream.id%}">x</a>)
          {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No ice cream is available.</p>
{% endif %}
{% if request.user.is_authenticated %}
<div>
  <a href="{% url 'menu:create' %}">Add a new flavor!</a> 
</div>
{% endif %}

{% if request.user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a>
{% endif %}

menu/templates/menu/index.html
{% load static %}

<h1> Welcome to Buster's Ice Cream</h1>
{% if request.user.is_authenticated %}
<h3>Welcome {{user.username}}!</h3>
{% else %}
<div><a href="{% url 'login'%}">Login</a> or <a href="{% url 'accounts:signup' %}">Sign Up</a></div>
{% endif %}
<br>
<nav>
  <a href="/menu/home">ALL</a>
  <a href="/menu/featured/">FEATURED</a>
  <a href="/menu/daily/">DAILY</a>
  <a href="/menu/weekly/">WEEKLY</a>
  <a href="/menu/seasonal/">SEASONAL</a>
</nav>
<h2> Select a menu from above or add a new flavor below!</h2>
{% if is_superuser_check %}
<div>
  <a href="{% url 'menu:create' %}">Add a new flavor!</a> 
</div>
{% endif %}

{% if request.user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a>
{% endif %}

polls/templates/polls/create.html
<!-- { % extends 'polls/base.html' %} -->
<!-- {% block content %} -->
<form method='POST'>{% csrf_token %}
  <!-- { % csrf_token % } -->
  {{form.as_p}}
  <button>Submit</button>
</form>
<!-- {% endblock content %} -->

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <!-- 
          Hard coded url version
          <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> 
        -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}: {{ choice.votes}}</li>
{% endfor %}
</ul>